version: '3'
  
services:


  # ng-web:
  #   image: node
  #   container_name: ng-web-server
  #   volumes:
  #     - "./frontend/angular:/app"
  #   command: bash -c "cd app && ./node_modules/@angular/cli/bin/ng serve --port 4201 --host 0.0.0.0 --disable-host-check"
  #   ports:
  #     - "4201:4201"

  # ng-mobi:
  #   image: node
  #   container_name: ng-mobi-server
  #   volumes:
  #     - "./frontend/angular:/app"
  #   command: bash -c "cd app && ./node_modules/@angular/cli/bin/ng serve mobi --port 4202 --host 0.0.0.0 --disable-host-check"
  #   ports:
  #     - "4202:4202"



  ij-ng-web:
    image: node
    container_name: ng-web-build
    tty: true
    volumes:
      - "./:/app"
    command: bash -c "cd app/frontend/angular && ./node_modules/@angular/cli/bin/ng build web --watch"


  ij-ng-mobi:
    image: node
    tty: true
    container_name: ng-mobi-build
    volumes:
      - "./:/app"
    command: bash -c "cd app/frontend/angular && ./node_modules/@angular/cli/bin/ng build mobi --watch"



  ij-django:
    container_name: django-server
    build: .
    tty: true
    command: bash -c "pip install -r requirements.txt && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8008"
    volumes:
      - "./backend:/app"
      - "./requirements.txt:/app/requirements.txt"
    ports:
      - "8081:8008"

  ij-nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes: 
      - "./config/vhost.nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - ij-ng-web
      - ij-ng-mobi
      - ij-django
       

      