#!/usr/bin/env python
from markdown2 import Markdown
import os
print('Start')
markdowner = Markdown()
lst = os.listdir('.')
print(lst)
for item in lst:
    if os.path.isfile(item):
        extension = os.path.splitext(item)[1]
        filename = os.path.splitext(item)[0]
        if extension == '.md':
            with open(item,'r') as f:
                print('Processing...%s' % item)
				
