# Generated by Django 3.0.7 on 2020-07-23 07:02

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('course', '0004_auto_20200719_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('publicname', models.CharField(default='', max_length=250, verbose_name='ФИО')),
                ('account', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='Счет')),
                ('phone', models.CharField(default='', max_length=250, verbose_name='Телефон')),
                ('telegram', models.CharField(default='', max_length=250, verbose_name='Телеграм')),
                ('skype', models.CharField(default='', max_length=250, verbose_name='Скайп')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=250, unique=True, verbose_name='Код')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Is activated?')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Пользователь')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.UserProfile', verbose_name='Пользователь')),
            ],
        ),
    ]
