# Generated by Django 3.0.7 on 2020-07-21 16:02

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('publicname', models.CharField(default='', max_length=250)),
                ('account', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('phone', models.CharField(default='', max_length=250)),
                ('telegram', models.CharField(default='', max_length=250)),
                ('skype', models.CharField(default='', max_length=250)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
