# Generated by Django 3.0.7 on 2020-09-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_replcredit_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account',
            field=models.IntegerField(default=6),
        ),
    ]
