# Generated by Django 3.0.7 on 2020-09-14 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_lesson_created'),
        ('cabinet', '0004_auto_20200914_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Lesson', verbose_name='Lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.UserProfile', verbose_name='Пользователь')),
            ],
        ),
    ]
