# Generated by Django 3.0.7 on 2020-07-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Name')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images', verbose_name='Image')),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('name_slug', models.CharField(blank=True, max_length=250, verbose_name='Name slug')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is published?')),
            ],
        ),
    ]
