# Generated by Django 3.0.7 on 2020-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lesson_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Number'),
        ),
    ]
