# Generated by Django 3.0.7 on 2020-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200710_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='video',
            field=models.CharField(blank=True, max_length=250, verbose_name='Name slug'),
        ),
    ]
