# Generated by Django 3.0.7 on 2020-07-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_lessonpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_youtube',
            field=models.BooleanField(default=False),
        ),
    ]
