# Generated by Django 3.0.7 on 2020-07-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_topic_is_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
