# Generated by Django 3.0.7 on 2020-07-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_lesson_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='desc',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='Description'),
        ),
    ]
