# Generated by Django 3.0.7 on 2020-07-17 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20200716_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Lesson'),
        ),
    ]
