# Generated by Django 3.0.7 on 2020-07-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_comments_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
