# Generated by Django 3.1.1 on 2020-09-12 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ij', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order2Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default='')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ij.control')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ij.option')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ij.order')),
            ],
        ),
    ]
