# Generated by Django 3.1.1 on 2020-09-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ij', '0002_order2control'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='controls',
            field=models.ManyToManyField(through='ij.Order2Control', to='ij.Control'),
        ),
    ]
