# Generated by Django 3.1 on 2020-08-30 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ij', '0002_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ij.subcategory'),
        ),
    ]
