# Generated by Django 3.1 on 2020-08-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ij', '0003_suggestion_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='text',
            field=models.CharField(db_index=True, default='', max_length=250, unique=True),
        ),
    ]
