# Generated by Django 3.1 on 2020-08-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ij', '0003_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='youdo_id',
            field=models.IntegerField(default=0),
        ),
    ]
