# Generated by Django 3.1.1 on 2020-09-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ij', '0005_proposition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proposition',
            new_name='Offer',
        ),
    ]
