# Generated by Django 3.1.1 on 2020-09-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ij', '0007_auto_20200913_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
